name: Node.js CI/CD

on:
  push:
    branches:
      - feature

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' 

      - name: Install dependencies
        run: npm install

      - name: Simple Smoke Test (Check if the app starts)
        run: |
          npm install express 
          node server.js &
          sleep 5
          curl -f http://localhost:3000 || { echo "Simple smoke test failed: Server not reachable"; exit 1; }
        env:
          PORT: 3000 
          
      - name: Deploy to AWS EC2
        if: success()
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: 'ubuntu'
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd test-actions
            lsof -ti:3000 | xargs -r kill -9 || true
            git pull origin feature
            screen -dmS node-app bash -c 'cd ~/test-actions && node server.js'